apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: demo-app
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "1000Mi"
    limits.cpu: "2000m"
    limits.memory: "1500Mi"
